version: '3'

tasks:
  check:
    desc: Lint Python scripts
    cmds:
      - uvx ruff check
      - uvx ty check

  fix:
    desc: Fix Python scripts
    cmds:
      - uvx ruff check --fix
      - uvx ruff format
