version: '3'

tasks:
  check:
    desc: Lint Python scripts
    cmds:
      - uvx ruff check --verbose .
      - uvx ty .

  fix:
    desc: Fix Python scripts
    cmds:
      - uvx ruff check --fix --verbose .
      - uvx ruff format .
