version: 2
registries:
  github-maven:
    type: maven-repository
    url: https://maven.pkg.github.com/aimarchirico/commons
    username: x-access-token
    password: ${{secrets.GH_PACKAGES_TOKEN}}

  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    scope: '@aimarchirico'
    token: ${{secrets.GH_PACKAGES_TOKEN}}

updates:
  - package-ecosystem: 'github-actions'
    directory: '/.github'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: 'gradle'
    directory: '/backend'
    schedule:
      interval: 'weekly'
    groups:
      gradle-minor-patch:
        update-types: ['minor', 'patch']
    registries:
      - github-maven

  - package-ecosystem: 'npm'
    directory: ['/frontend', '/tools']
    schedule:
      interval: 'weekly'
    groups:
      npm-minor-patch:
        update-types: ['minor', 'patch']
    registries:
      - github-npm
    cooldown:
      default-days: 1
