packages:
  - "apps/*"
  - "packages/features/*"
  - "packages/shared/*"
allowBuilds:
  '@openapitools/openapi-generator-cli': true
  core-js: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aimarchirico/commons-expo@0.1.1 || 0.1.2 || 0.1.3 || 1.1.0'
  - '@aimarchirico/commons-ts@0.1.1 || 0.1.2 || 0.1.3 || 0.1.4 || 1.1.0'
  - '@aimarchirico/commons-openapi@1.1.0'
