packages:
  - "apps/*"
  - "packages/features/*"
  - "packages/shared/*"
allowBuilds:
  '@openapitools/openapi-generator-cli': true
  core-js: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aimarchirico/core-expo@0.1.1 || 0.1.2 || 0.1.3'
  - '@aimarchirico/core-ts@0.1.1 || 0.1.2 || 0.1.3 || 0.1.4'
