version: '3'

tasks:
  install:
    internal: true
    desc: Install NPM dependencies
    cmds:
      - pnpm install
      - task: api
    if: '[ -n "$CI" ]'

  check:
    desc: Check TypeScript files
    cmds:
      - task: install
      - pnpm turbo run check

  fix:
    desc: Fix TypeScript files
    cmds:
      - pnpm turbo run fix

  run:
    desc: Start dev server
    cmds:
      - pnpm --filter ./apps/expo dev

  build:
    desc: Build development APK
    cmds:
      - pnpm --filter ./apps/expo build:debug

  api:
    desc: Generate OpenAPI client code and docs
    env:
      API_CLIENT_OUTPUT_DIR: '{{.TASKFILE_DIR}}/packages/shared/api-client/src/generated'
      API_DOCS_OUTPUT_DIR: '{{.TASKFILE_DIR}}/../docs'
    cmds:
      - cmd: pnpm --filter ./packages/shared/api-client api
        ignore_error: true

  build:android:
    desc: Build release for Android
    cmds:
      - task: install
      - pnpm --filter ./apps/expo prebuild
      - pnpm --filter ./apps/expo build:release

  build:web:
    desc: Build release for web
    cmds:
      - task: install
      - pnpm --filter ./apps/expo export
      - pnpm --filter ./apps/expo cloudflare:fix
