version: '3'

tasks:
  run:
    desc: Start dev server
    cmds:
      - pnpm install
      - pnpm --filter @template/expo start

  check:
    desc: Run lint and type checks
    cmds:
      - pnpm turbo run check

  fix:
    desc: Fix lint problems
    cmds:
      - pnpm turbo run fix

  build:
    desc: Build development apk
    cmds:
      - pnpm install
      - pnpm turbo run build --filter=@template/expo

  api:
    desc: Generate OpenAPI client code and docs
    cmds:
      - task: :api

  ci:check:
    desc: Run CI checks
    cmds:
      - pnpm install --frozen-lockfile
      - pnpm turbo run api
      - pnpm turbo run check

  ci:android:
    desc: Run CI build for android
    cmds:
      - task: ci:check
      - pnpm --filter @template/expo build
      - cd apps/expo/android && bash gradlew assembleRelease

  ci:web:
    desc: Run CI build for web
    cmds:
      - task: ci:check
      - pnpm --filter @template/expo export:web
      # Fix node modules asset paths for Cloudflare Pages
      - |
        if [ -d apps/expo/dist/assets/node_modules ]; then
          mv apps/expo/dist/assets/node_modules/* apps/expo/dist/assets/ || true
          rm -rf apps/expo/dist/assets/node_modules
        fi
        find apps/expo/dist/_expo/static/js/web/ -type f -print0 | xargs -0 sed -i 's/assets\/node_modules/assets/g'
      - cp -r functions apps/expo/dist/functions
      - cp public/_routes.json apps/expo/dist/_routes.json
