version: '3'

dotenv: ['.env']

includes:
  tools:
    taskfile: ./tools/Taskfile.yaml
    dir: ./tools
    flatten: true
  github:
    taskfile: ./.github/Taskfile.yaml
    dir: ./.github
  backend:
    taskfile: ./backend/Taskfile.yaml
    dir: ./backend
  frontend:
    taskfile: ./frontend/Taskfile.yaml
    dir: ./frontend
  init:
    taskfile: ./init/Taskfile.yaml
    dir: ./init

tasks:
  default:
    cmds:
      - task --list
