version: '3'

dotenv: ['.env']

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api
  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client
  tools:
    taskfile: ./tools/Taskfile.yml
    dir: ./tools
    flatten: true

tasks:
  default:
    cmds:
      - task --list
