includes:
  core:
    taskfile: ../../core/gradle/Taskfile.yml
    dir: .
    optional: true

tasks:
  run:
    desc: Start API server
    cmds:
      - bash gradlew bootRun

  check:
    desc: Compile and run tests for the Kotlin backend
    cmds:
      - sh: "[ -f ../../core/gradle/Taskfile.yml ] && task core:check || bash gradlew check"

  fix:
    desc: Fix formatting problems
    cmds:
      - sh: "[ -f ../../core/gradle/Taskfile.yml ] && task core:fix || bash gradlew ktfmtFormat"

  up:
    desc: Start the database container
    cmds:
      - docker compose up -d

  down:
    desc: Stop the database container
    cmds:
      - docker compose down
