version: '3'

tasks:
  check:
    desc: Check Kotlin files
    cmds:
      - bash gradlew check

  fix:
    desc: Fix Kotlin files
    cmds:
      - bash gradlew ktfmtFormat

  run:
    desc: Start API server
    dotenv: ['.env']
    cmds:
      - bash gradlew :app:bootRun

  up:
    desc: Start database container
    cmds:
      - docker compose up -d

  down:
    desc: Stop database container
    cmds:
      - docker compose down
