version: '3'

tasks:
  check:
    desc: Run tests and lint
    cmds:
      - task: docker:check
      - bash gradlew check

  docker:check:
    desc: Lint Dockerfiles
    cmds:
      - 'find . -type d \( -name "node_modules" -o -name ".git" \) -prune -o -name "Dockerfile" -print | xargs -r docker run --rm -v $(pwd):/repo --workdir /repo hadolint/hadolint:latest hadolint -c .hadolint.yaml'

  fix:
    desc: Format Kotlin files
    cmds:
      - bash gradlew ktfmtFormat

  run:
    desc: Start API server
    dotenv: ['.env']
    cmds:
      - bash gradlew :app:bootRun

  up:
    desc: Start the database container
    cmds:
      - docker compose up -d

  down:
    desc: Stop the database container
    cmds:
      - docker compose down
