version: '3'

tasks:
  check:
    desc: Run tests and lint
    cmds:
      - bash gradlew check

  fix:
    desc: Format Kotlin files
    cmds:
      - bash gradlew ktfmtFormat

  run:
    desc: Start API server
    dotenv: ['.env']
    cmds:
      - bash gradlew :app:bootRun

  up:
    desc: Start the database container
    cmds:
      - docker compose up -d

  down:
    desc: Stop the database container
    cmds:
      - docker compose down
