[versions]
kotlin = "2.4.0"
spring-boot = "4.1.0"
hypersistence = "3.15.3"
springdoc = "3.0.3"
ktfmt = "0.26.0"
archunit = "1.4.2"
commons-security = "2.0.1"
commons-test = "2.0.0"
commons-convention="1.2.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-noarg = { module = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlin" }
spring-boot-gradlePlugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

hypersistence-utils = { module = "io.hypersistence:hypersistence-utils-hibernate-73", version.ref = "hypersistence" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
ktfmt-gradlePlugin = { module = "com.ncorti.ktfmt.gradle:com.ncorti.ktfmt.gradle.gradle.plugin", version.ref = "ktfmt" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
commons-security = { module = "no.chirico.commons:commons-security", version.ref = "commons-security" }
commons-test = { module = "no.chirico.commons:commons-test", version.ref = "commons-test" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
commons-kotlin = { id = "no.chirico.commons.convention.kotlin", version.ref = "commons-convention" }
commons-spring = { id = "no.chirico.commons.convention.spring", version.ref = "commons-convention" }
commons-architecture = { id = "no.chirico.commons.convention.architecture", version.ref = "commons-convention" }
