minimumReleaseAgeExclude:
  - '@aimarchirico/commons-ts'
  - '@aimarchirico/commons-cloudflare@3.1.0 || 3.2.0'
  - '@aimarchirico/commons-expo@4.1.0'
  - '@aimarchirico/commons-github@1.0.0'
  - '@aimarchirico/commons-project@1.0.0'
packages: []
allowBuilds:
  dtrace-provider: true
  esbuild: true
  unrs-resolver: true
