minimumReleaseAgeExclude:
  - '@aimarchirico/commons-ts'
  - '@aimarchirico/commons-cloudflare@3.1.0 || 3.2.0 || 3.3.0 || 3.5.0'
  - '@aimarchirico/commons-expo@4.1.0 || 4.2.0 || 4.4.0'
  - '@aimarchirico/commons-github@1.0.0 || 1.1.0 || 1.1.1 || 1.1.2 || 1.3.0'
  - '@aimarchirico/commons-project@1.0.0 || 1.1.0 || 1.3.0'
packages: []
allowBuilds:
  dtrace-provider: true
  esbuild: true
  unrs-resolver: true
