version: '3'

tasks:
  install:
    internal: true
    desc: Install npm dependencies
    cmds:
      - pnpm install
    if: '[ -n "$CI" ]'

  docs:check:
    desc: Lint Markdown files
    dir: ..
    cmds:
      - task: install
      - tools/node_modules/.bin/markdownlint-cli2 --config tools/.markdownlint-cli2.cjs

  docs:fix:
    desc: Fix Markdown issues
    dir: ..
    cmds:
      - tools/node_modules/.bin/markdownlint-cli2 --config tools/.markdownlint-cli2.cjs --fix

  commit:check:
    desc: Lint commit messages
    vars:
      EDIT:
        sh: |
          if [ -n "$EDIT_FILE" ]; then
            echo "--edit $EDIT_FILE"
          fi
      COMMIT_RANGE:
        sh: |
          if [ -n "$FROM_SHA" ] && [ -n "$TO_SHA" ]; then
            echo "--from $FROM_SHA --to $TO_SHA"
          fi
    cmds:
      - task: install
      - pnpm exec commitlint {{.COMMIT_RANGE}} {{.EDIT}}

  skills:
    cmds:
      - gh skill install aimarchirico/commons --all --scope project --agent antigravity
      - gh skill install aimarchirico/commons --all --scope project --agent claude-code

  root:check:
    desc: Lint global repository folders
    dir: ..
    cmds:
      - ./tools/node_modules/.bin/eslint --config tools/eslint.config.ts --no-error-on-unmatched-pattern ".github/**/*" "tools/**/*" ".vscode/**/*" "init/**/*" "*.yml" "*.json"

  root:fix:
    desc: Fix global repository folders lint issues
    dir: ..
    cmds:
      - ./tools/node_modules/.bin/eslint --config tools/eslint.config.ts --no-error-on-unmatched-pattern ".github/**/*" "tools/**/*" ".vscode/**/*" "init/**/*" "*.yml" "*.json" --fix

  shell:check:
    desc: Lint shell scripts
    dir: ..
    cmds:
      - 'find . -type d \( -name "node_modules" -o -name ".git" \) -prune -o -name "*.sh" -print | xargs -r docker run --rm -v $(pwd):/repo --workdir /repo koalaman/shellcheck:latest shellcheck --rcfile=tools/node_modules/@aimarchirico/commons-tools/.shellcheckrc'

  action:check:
    desc: Lint GitHub Actions
    dir: ..
    cmds:
      - docker run --rm -v $(pwd):/repo --workdir /repo rhysd/actionlint:latest -color -config tools/node_modules/@aimarchirico/commons-tools/actionlint.yaml

  docker:check:
    desc: Lint Dockerfiles
    dir: ..
    cmds:
      - 'find . -type d \( -name "node_modules" -o -name ".git" \) -prune -o -name "Dockerfile" -print | xargs -r docker run --rm -v $(pwd):/repo --workdir /repo hadolint/hadolint:latest hadolint -c tools/node_modules/@aimarchirico/commons-tools/.hadolint.yaml'