version: '3'

tasks:
  install:
    internal: true
    desc: Install npm dependencies
    cmds:
      - pnpm install
    if: '[ -n "$CI" ]'

  docs:check:
    desc: Lint Markdown files
    cmds:
      - task: install
      - pnpm exec markdownlint-cli2

  docs:fix:
    desc: Fix Markdown issues
    cmds:
      - pnpm exec markdownlint-cli2 --fix

  commit:check:
    desc: Lint commit messages
    vars:
      EDIT:
        sh: |
          if [ -n "$EDIT_FILE" ]; then
            echo "--edit $EDIT_FILE"
          fi
      COMMIT_RANGE:
        sh: |
          if [ -n "$FROM_SHA" ] && [ -n "$TO_SHA" ]; then
            echo "--from $FROM_SHA --to $TO_SHA"
          fi
    cmds:
      - task: install
      - pnpm exec commitlint {{.COMMIT_RANGE}} {{.EDIT}}

  skills:
    cmds:
      - gh skill install aimarchirico/commons --all --scope project --agent antigravity