name: Backend - CI

on:
  push:
    branches: [main, dev]
    paths: [backend/**]
  pull_request:
    branches: [main, dev]
    paths: [backend/**]

jobs:
  ci:
    uses: aimarchirico/core/.github/workflows/reusable-backend-ci.yml@dev
