name: Backend - CI

on:
  push:
    branches: [main]
    paths: [backend/**]
  pull_request:
    branches: [main]
    paths: [backend/**]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Set Up Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run Checks
        run: task check
