name: CI

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: CI
    uses: aimarchirico/commons/.github/workflows/reusable-ci.yml@main
    secrets: inherit
