name: Deploy

on:
  workflow_call:
    inputs:
      deploy-api:
        type: boolean
        default: false
      deploy-web:
        type: boolean
        default: false

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy
    uses: aimarchirico/commons/.github/workflows/reusable-deploy.yml@main
    with:
      deploy-api: ${{ inputs.deploy-api }}
      deploy-web: ${{ inputs.deploy-web }}
    secrets: inherit
