name: Deploy Web

on:
  workflow_call:

permissions:
  contents: read
  deployments: write

jobs:
  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    environment:
      name: web-production
      url: ${{ vars.DEPLOYMENT_URL }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: aimarchirico/core/.github/actions/setup-node@dev
        with:
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Build for Web
        run: task build:web
        working-directory: ./frontend
        env:
          API_URL: ${{ vars.API_URL }}
          CF_ACCESS_CLIENT_ID: ${{ vars.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

      - name: Publish to Cloudflare Pages
        working-directory: ./frontend
        run: npx wrangler pages deploy ./apps/expo/dist --project-name=template --branch=main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
