name: Docs - CI

on:
  push:
    branches: [main, dev]
    paths:
      - "**/*.md"
      - ".github/workflows/docs-ci.yml"
      - "Taskfile.yml"
      - "tools/package.json"
      - "tools/pnpm-lock.yaml"
  pull_request:
    branches: [main, dev]
    paths:
      - "**/*.md"
      - ".github/workflows/docs-ci.yml"
      - "Taskfile.yml"
      - "tools/package.json"
      - "tools/pnpm-lock.yaml"

jobs:
  ci:
    uses: aimarchirico/core/.github/workflows/reusable-docs-ci.yml@dev
