name: Frontend - Android

on:
  push:
    tags:
      - 'frontend-v*'

permissions:
  contents: write

jobs:
  deploy:
    name: Build and Release Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get Version from Tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/frontend-v}"
          if [ "$VERSION" = "$GITHUB_REF" ]; then VERSION="dev"; fi
          echo "VERSION_NAME=$VERSION" >> $GITHUB_OUTPUT

      - name: Run CI Build
        run: task ci:android
        working-directory: ./frontend
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          API_URL: ${{ vars.API_URL }}
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
          VERSION_NAME: ${{ steps.get_version.outputs.VERSION_NAME }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases

      - name: Copy APK
        run: cp ./frontend/android/app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/app-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ steps.get_version.outputs.VERSION_NAME}}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app-release.apk
          asset_name: template-${{ steps.get_version.outputs.VERSION_NAME}}.apk
          asset_content_type: application/vnd.android.package-archive
