name: Npm - CI

on:
  push:
    branches: [main, dev]
    paths: [npm/**]
  pull_request:
    branches: [main, dev]
    paths: [npm/**]

jobs:
  ci:
    uses: aimarchirico/core/.github/workflows/reusable-frontend-ci.yml@dev
    secrets: inherit

