name: Sub-Issues

on:
  issues:
    types: [assigned, closed]
  pull_request:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: read

jobs:
  assign:
    name: Assign Sub-Issues
    if: github.event_name == 'issues' && github.event.action == 'assigned'
    runs-on: ubuntu-latest
    steps:
      - uses: aimarchirico/commons/.github/actions/assign-sub-issues@main

  close:
    name: Close Sub-Issues
    if: github.event_name == 'issues' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: aimarchirico/commons/.github/actions/close-sub-issues@main

  move-in-progress:
    name: Move Sub-Issues In Progress
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: aimarchirico/commons/.github/actions/move-sub-issues-in-progress@main
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          project-number: '2'
